# Generated by Django 4.2.15 on 2024-09-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_delete_user_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
