# Generated by Django 4.2.15 on 2024-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_studentprofile_pursuing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='education_type',
            field=models.CharField(max_length=10),
        ),
    ]
<<<<<<< HEAD

=======
>>>>>>> 98d37efb9be47e16adf9aed41527384eac7a96fb
