# Generated by Django 4.2.15 on 2024-09-27 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0022_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='education_type',
            field=models.CharField(blank=True, choices=[('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
