# Generated by Django 4.2.15 on 2024-09-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_studentprofile_education_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='books_obtained',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='education_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pursuing_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='select_branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
