# Generated by Django 4.2.15 on 2024-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_studentprofile_pursuing_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='books_obtained',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pursuing_year',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='select_branch',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_image',
            field=models.ImageField(default=None, upload_to='student_info/'),
        ),
    ]
